import type { Lesson } from "./types";

export const lessons: Lesson[] = [
  // ============================================
  // TMUX - BEGINNER
  // ============================================
  {
    id: "tmux-basics-1",
    title: "Understanding tmux Prefix",
    description: "Learn the foundation of all tmux commands - the prefix key",
    category: "tmux",
    difficulty: "beginner",
    estimatedMinutes: 3,
    steps: [
      {
        id: "step-1",
        instruction: "The prefix key is how tmux knows you're talking to it, not your terminal. Press Ctrl+a to activate the prefix.",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a' at the same time",
        successMessage: "Prefix activated! You'll see a brief indicator.",
      },
      {
        id: "step-2",
        instruction: "Alternative prefix: You can also use Ctrl+b (the default tmux prefix). Try it now.",
        expectedKeys: ["Ctrl-b"],
        hint: "Hold Ctrl and press 'b'",
        successMessage: "Both Ctrl+a and Ctrl+b work as prefix keys!",
      },
    ],
  },
  {
    id: "tmux-split-panes",
    title: "Splitting Panes",
    description: "Learn to split your terminal into multiple panes",
    category: "tmux",
    difficulty: "beginner",
    estimatedMinutes: 5,
    steps: [
      {
        id: "step-1",
        instruction: "First, activate the prefix with Ctrl+a",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-2",
        instruction: "Now press - (minus) to split horizontally (top/bottom)",
        expectedKeys: ["-"],
        hint: "Press the minus key on your keyboard",
        successMessage: "You created a horizontal split!",
      },
      {
        id: "step-3",
        instruction: "Let's try a vertical split. First, press the prefix Ctrl+a",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-4",
        instruction: "Now press _ (underscore/Shift+minus) to split vertically (left/right)",
        expectedKeys: ["_"],
        hint: "Press Shift+Minus to get underscore",
        successMessage: "You created a vertical split! You now have multiple panes.",
      },
    ],
  },
  {
    id: "tmux-navigate-panes",
    title: "Navigating Between Panes",
    description: "Move between panes using vim-style navigation",
    category: "tmux",
    difficulty: "beginner",
    estimatedMinutes: 5,
    steps: [
      {
        id: "step-1",
        instruction: "With multiple panes, you need to move between them. Press Ctrl+a to start.",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-2",
        instruction: "Press 'h' to move to the left pane (like vim!)",
        expectedKeys: ["h"],
        hint: "Press the 'h' key",
        successMessage: "You moved left!",
      },
      {
        id: "step-3",
        instruction: "Press Ctrl+a then 'j' to move down",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-4",
        instruction: "Press 'j' to move to the pane below",
        expectedKeys: ["j"],
        hint: "Press the 'j' key",
        successMessage: "Moved down! h/j/k/l for left/down/up/right navigation.",
      },
      {
        id: "step-5",
        instruction: "Now try moving up. Press Ctrl+a first.",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-6",
        instruction: "Press 'k' to move up",
        expectedKeys: ["k"],
        hint: "Press the 'k' key",
        successMessage: "Moved up!",
      },
      {
        id: "step-7",
        instruction: "Finally, Ctrl+a then 'l' to move right",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-8",
        instruction: "Press 'l' to move to the right pane",
        expectedKeys: ["l"],
        hint: "Press the 'l' key",
        successMessage: "Perfect! You've mastered pane navigation!",
      },
    ],
  },
  {
    id: "tmux-windows",
    title: "Working with Windows",
    description: "Create and switch between tmux windows (like browser tabs)",
    category: "tmux",
    difficulty: "beginner",
    estimatedMinutes: 5,
    steps: [
      {
        id: "step-1",
        instruction: "Windows are like tabs. Create a new window with Ctrl+a then 'c'",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-2",
        instruction: "Press 'c' to create a new window",
        expectedKeys: ["c"],
        hint: "Press the 'c' key (c for create)",
        successMessage: "New window created! Look at the status bar at the bottom.",
      },
      {
        id: "step-3",
        instruction: "Switch to window 0 with Ctrl+a then '0'",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-4",
        instruction: "Press '0' to switch to the first window",
        expectedKeys: ["0"],
        hint: "Press the number '0' key",
        successMessage: "You're back at window 0! Use numbers 0-9 to switch windows.",
      },
      {
        id: "step-5",
        instruction: "Quick switch to last window: Ctrl+a",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-6",
        instruction: "Press Tab to go to last active window",
        expectedKeys: ["Tab"],
        hint: "Press the Tab key",
        successMessage: "Tab quickly toggles between your two most recent windows!",
      },
    ],
  },
  {
    id: "tmux-pane-resize",
    title: "Resizing Panes",
    description: "Adjust pane sizes to fit your workflow",
    category: "tmux",
    difficulty: "beginner",
    estimatedMinutes: 4,
    steps: [
      {
        id: "step-1",
        instruction: "Resize panes with capital H/J/K/L. Press Ctrl+a first.",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-2",
        instruction: "Press 'H' (Shift+h) to resize left",
        expectedKeys: ["H"],
        hint: "Press Shift+h for capital H",
        successMessage: "Resized left! Capital letters = resize, lowercase = navigate.",
      },
      {
        id: "step-3",
        instruction: "Ctrl+a then 'L' to resize right",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-4",
        instruction: "Press 'L' (Shift+l) to resize right",
        expectedKeys: ["L"],
        hint: "Press Shift+l for capital L",
        successMessage: "Resized right! Use J and K for vertical resizing.",
      },
    ],
  },
  {
    id: "tmux-zoom",
    title: "Zoom & Maximize Panes",
    description: "Focus on one pane by zooming it",
    category: "tmux",
    difficulty: "beginner",
    estimatedMinutes: 3,
    steps: [
      {
        id: "step-1",
        instruction: "Sometimes you need to focus on one pane. Press Ctrl+a first.",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-2",
        instruction: "Press 'z' to zoom/maximize the current pane",
        expectedKeys: ["z"],
        hint: "Press 'z' for zoom",
        successMessage: "Zoomed! The pane is now fullscreen. Press z again to unzoom.",
      },
      {
        id: "step-3",
        instruction: "Or use + for maximize. Press Ctrl+a first.",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-4",
        instruction: "Press '+' to toggle maximize/restore",
        expectedKeys: ["+"],
        hint: "Press Shift+= for +",
        successMessage: "Both z and + work for zoom!",
      },
    ],
  },

  // ============================================
  // TMUX - INTERMEDIATE
  // ============================================
  {
    id: "tmux-copy-mode",
    title: "Copy Mode",
    description: "Learn to scroll and copy text in tmux",
    category: "tmux",
    difficulty: "intermediate",
    estimatedMinutes: 7,
    steps: [
      {
        id: "step-1",
        instruction: "Enter copy mode to scroll and select text. Press Ctrl+a",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-2",
        instruction: "Press '[' to enter copy mode",
        expectedKeys: ["["],
        hint: "Press the '[' key (left bracket)",
        successMessage: "You're in copy mode! You can now scroll with j/k or arrow keys.",
      },
      {
        id: "step-3",
        instruction: "Move around with j (down) to scroll through history",
        expectedKeys: ["j"],
        hint: "Press 'j' to move down",
        successMessage: "You can scroll through all your terminal history!",
      },
      {
        id: "step-4",
        instruction: "In copy mode, press 'v' to start selecting text",
        expectedKeys: ["v"],
        hint: "Press 'v' to begin selection",
        successMessage: "Selection started! Move around to select text.",
      },
      {
        id: "step-5",
        instruction: "Press 'y' to copy the selection and exit copy mode",
        expectedKeys: ["y"],
        hint: "Press 'y' to yank (copy)",
        successMessage: "Text copied to tmux buffer!",
      },
      {
        id: "step-6",
        instruction: "Now paste it. Press Ctrl+a first.",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-7",
        instruction: "Press 'p' to paste",
        expectedKeys: ["p"],
        hint: "Press 'p' to paste",
        successMessage: "Pasted! Copy mode is incredibly useful for grabbing command output.",
      },
    ],
  },
  {
    id: "tmux-sessions",
    title: "Session Management",
    description: "Create, switch, and manage tmux sessions",
    category: "tmux",
    difficulty: "intermediate",
    estimatedMinutes: 8,
    steps: [
      {
        id: "step-1",
        instruction: "Sessions let you organize work by project. Press Ctrl+a to start.",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-2",
        instruction: "Press '$' to rename the current session",
        expectedKeys: ["$"],
        hint: "Press Shift+4 to get '$'",
        successMessage: "Now you can type a new session name!",
      },
      {
        id: "step-3",
        instruction: "List all sessions. Press Ctrl+a first.",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-4",
        instruction: "Press 'w' to list windows/sessions",
        expectedKeys: ["w"],
        hint: "Press 'w' for window list",
        successMessage: "You can see all sessions and windows here!",
      },
      {
        id: "step-5",
        instruction: "To detach from a session (it keeps running), press Ctrl+a",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-6",
        instruction: "Press 'd' to detach. You can reattach later with 'tmux attach'",
        expectedKeys: ["d"],
        hint: "Press 'd' for detach",
        successMessage: "Session detached! It continues running in the background.",
      },
    ],
  },
  {
    id: "tmux-pane-management",
    title: "Advanced Pane Operations",
    description: "Swap, break, and close panes",
    category: "tmux",
    difficulty: "intermediate",
    estimatedMinutes: 6,
    steps: [
      {
        id: "step-1",
        instruction: "Swap the current pane with the next one. Press Ctrl+a",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-2",
        instruction: "Press '>' to swap with the next pane",
        expectedKeys: [">"],
        hint: "Press Shift+. for >",
        successMessage: "Panes swapped!",
      },
      {
        id: "step-3",
        instruction: "Break a pane into its own window. Press Ctrl+a",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-4",
        instruction: "Press '!' to break pane to a new window",
        expectedKeys: ["!"],
        hint: "Press Shift+1 for !",
        successMessage: "Pane is now its own window!",
      },
      {
        id: "step-5",
        instruction: "Close a pane. Press Ctrl+a",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-6",
        instruction: "Press 'x' to close/kill the current pane",
        expectedKeys: ["x"],
        hint: "Press 'x' to kill pane",
        successMessage: "Pane closed! (You'll be asked to confirm)",
      },
    ],
  },
  {
    id: "tmux-config",
    title: "Configuration & Utilities",
    description: "Reload config, toggle mouse, and more",
    category: "tmux",
    difficulty: "intermediate",
    estimatedMinutes: 5,
    steps: [
      {
        id: "step-1",
        instruction: "Reload tmux config after making changes. Press Ctrl+a",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-2",
        instruction: "Press 'r' to reload configuration",
        expectedKeys: ["r"],
        hint: "Press 'r' for reload",
        successMessage: "Config reloaded! Changes take effect immediately.",
      },
      {
        id: "step-3",
        instruction: "Toggle mouse mode. Press Ctrl+a",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-4",
        instruction: "Press 'm' to toggle mouse mode",
        expectedKeys: ["m"],
        hint: "Press 'm' for mouse",
        successMessage: "Mouse toggled! You can now click to select panes when enabled.",
      },
      {
        id: "step-5",
        instruction: "See all keybindings. Press Ctrl+a",
        expectedKeys: ["Ctrl-a"],
        hint: "Hold Ctrl and press 'a'",
        successMessage: "Prefix activated!",
      },
      {
        id: "step-6",
        instruction: "Press '?' to see all key bindings",
        expectedKeys: ["?"],
        hint: "Press Shift+/ for ?",
        successMessage: "This shows ALL tmux keybindings. Very useful reference!",
      },
    ],
  },

  // ============================================
  // NEOVIM - BEGINNER
  // ============================================
  {
    id: "vim-modes-intro",
    title: "Understanding Vim Modes",
    description: "The most important concept in Vim - modal editing",
    category: "neovim",
    difficulty: "beginner",
    estimatedMinutes: 5,
    steps: [
      {
        id: "step-1",
        instruction: "Vim has modes. You start in NORMAL mode. Press 'i' to enter INSERT mode.",
        expectedKeys: ["i"],
        hint: "Press the 'i' key",
        successMessage: "You're in INSERT mode! Now you can type text.",
      },
      {
        id: "step-2",
        instruction: "To go back to NORMAL mode, press Escape. This is the most important key!",
        expectedKeys: ["Escape"],
        hint: "Press the Escape key (top-left of keyboard)",
        successMessage: "Back to NORMAL mode! Escape is your safe key.",
      },
      {
        id: "step-3",
        instruction: "In NORMAL mode, press 'v' to enter VISUAL mode for selecting text.",
        expectedKeys: ["v"],
        hint: "Press the 'v' key",
        successMessage: "VISUAL mode! Move cursor to select text.",
      },
      {
        id: "step-4",
        instruction: "Press Escape to return to NORMAL mode",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "Great! Remember: Escape always brings you back to NORMAL mode.",
      },
      {
        id: "step-5",
        instruction: "Try VISUAL LINE mode. Press 'V' (capital V)",
        expectedKeys: ["V"],
        hint: "Press Shift+v for capital V",
        successMessage: "VISUAL LINE selects entire lines at once!",
      },
      {
        id: "step-6",
        instruction: "Press Escape to exit",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "You've learned the three main modes: NORMAL, INSERT, and VISUAL!",
      },
    ],
  },
  {
    id: "vim-basic-movement",
    title: "Basic Cursor Movement",
    description: "Navigate with h, j, k, l instead of arrow keys",
    category: "neovim",
    difficulty: "beginner",
    estimatedMinutes: 5,
    steps: [
      {
        id: "step-1",
        instruction: "In NORMAL mode, press 'h' to move LEFT (think: h is on the left)",
        expectedKeys: ["h"],
        hint: "Press 'h' to move left",
        successMessage: "Left! The h key moves cursor left.",
      },
      {
        id: "step-2",
        instruction: "Press 'l' to move RIGHT (think: l is on the right)",
        expectedKeys: ["l"],
        hint: "Press 'l' to move right",
        successMessage: "Right! The l key moves cursor right.",
      },
      {
        id: "step-3",
        instruction: "Press 'j' to move DOWN (think: j hangs down like a hook)",
        expectedKeys: ["j"],
        hint: "Press 'j' to move down",
        successMessage: "Down! The j key moves cursor down.",
      },
      {
        id: "step-4",
        instruction: "Press 'k' to move UP (think: k points up)",
        expectedKeys: ["k"],
        hint: "Press 'k' to move up",
        successMessage: "Up! h-j-k-l keeps your fingers on home row.",
      },
    ],
  },
  {
    id: "vim-word-movement",
    title: "Word-Based Movement",
    description: "Move faster by jumping between words",
    category: "neovim",
    difficulty: "beginner",
    estimatedMinutes: 4,
    steps: [
      {
        id: "step-1",
        instruction: "Press 'w' to jump to the next word",
        expectedKeys: ["w"],
        hint: "Press 'w' for word forward",
        successMessage: "Word forward! Much faster than pressing l multiple times.",
      },
      {
        id: "step-2",
        instruction: "Press 'b' to jump back to the previous word",
        expectedKeys: ["b"],
        hint: "Press 'b' for back",
        successMessage: "Word back! Use w and b to navigate quickly.",
      },
      {
        id: "step-3",
        instruction: "Press 'e' to jump to the end of the current/next word",
        expectedKeys: ["e"],
        hint: "Press 'e' for end of word",
        successMessage: "End of word! w/b/e are your word navigation tools.",
      },
    ],
  },
  {
    id: "vim-line-movement",
    title: "Line Navigation",
    description: "Jump to start, end, and specific lines",
    category: "neovim",
    difficulty: "beginner",
    estimatedMinutes: 4,
    steps: [
      {
        id: "step-1",
        instruction: "Press '0' to jump to the start of the line",
        expectedKeys: ["0"],
        hint: "Press the number '0' key",
        successMessage: "Start of line! Zero takes you to column 0.",
      },
      {
        id: "step-2",
        instruction: "Press '^' to jump to the first non-blank character",
        expectedKeys: ["^"],
        hint: "Press Shift+6 for '^'",
        successMessage: "First non-blank! Useful for indented code.",
      },
      {
        id: "step-3",
        instruction: "Press '$' to jump to the end of the line",
        expectedKeys: ["$"],
        hint: "Press Shift+4 for '$'",
        successMessage: "End of line! $ is the regex symbol for 'end'.",
      },
      {
        id: "step-4",
        instruction: "Press 'G' (capital G) to go to the last line of the file",
        expectedKeys: ["G"],
        hint: "Press Shift+g for capital G",
        successMessage: "Bottom of file! G goes to the end.",
      },
      {
        id: "step-5",
        instruction: "Press 'g' twice quickly (gg) to go to the first line",
        expectedKeys: ["g"],
        hint: "Press 'g' (we'll simulate gg with just g for now)",
        successMessage: "Top of file! gg goes to the beginning.",
      },
    ],
  },
  {
    id: "vim-insert-modes",
    title: "Ways to Enter Insert Mode",
    description: "Multiple ways to start typing - each with a purpose",
    category: "neovim",
    difficulty: "beginner",
    estimatedMinutes: 6,
    steps: [
      {
        id: "step-1",
        instruction: "Press 'i' to insert BEFORE the cursor",
        expectedKeys: ["i"],
        hint: "Press 'i' for insert",
        successMessage: "Insert mode! Cursor didn't move, you type before it.",
      },
      {
        id: "step-2",
        instruction: "Press Escape, then try 'a' to APPEND after the cursor",
        expectedKeys: ["Escape"],
        hint: "Press Escape first",
        successMessage: "Back to normal mode!",
      },
      {
        id: "step-3",
        instruction: "Now press 'a' to append",
        expectedKeys: ["a"],
        hint: "Press 'a' for append",
        successMessage: "Append mode! Cursor moved right, you type after it.",
      },
      {
        id: "step-4",
        instruction: "Press Escape, then 'I' (capital I) to insert at line start",
        expectedKeys: ["Escape"],
        hint: "Press Escape first",
        successMessage: "Back to normal mode!",
      },
      {
        id: "step-5",
        instruction: "Press 'I' (Shift+i) to insert at the beginning of the line",
        expectedKeys: ["I"],
        hint: "Press Shift+i for capital I",
        successMessage: "Insert at line start! Great for adding to the beginning.",
      },
      {
        id: "step-6",
        instruction: "Press Escape, then 'A' to append at line end",
        expectedKeys: ["Escape"],
        hint: "Press Escape first",
        successMessage: "Back to normal mode!",
      },
      {
        id: "step-7",
        instruction: "Press 'A' (Shift+a) to append at the end of the line",
        expectedKeys: ["A"],
        hint: "Press Shift+a for capital A",
        successMessage: "Append at line end! Perfect for adding semicolons.",
      },
      {
        id: "step-8",
        instruction: "Press Escape, then 'o' to open a new line below",
        expectedKeys: ["Escape"],
        hint: "Press Escape first",
        successMessage: "Back to normal mode!",
      },
      {
        id: "step-9",
        instruction: "Press 'o' to open a new line below and enter insert mode",
        expectedKeys: ["o"],
        hint: "Press 'o' for open line below",
        successMessage: "New line below! 'O' (capital) opens above.",
      },
    ],
  },
  {
    id: "vim-basic-editing",
    title: "Basic Editing Operations",
    description: "Delete, undo, and repeat commands",
    category: "neovim",
    difficulty: "beginner",
    estimatedMinutes: 5,
    steps: [
      {
        id: "step-1",
        instruction: "Press 'x' to delete the character under the cursor",
        expectedKeys: ["x"],
        hint: "Press 'x' to delete character",
        successMessage: "Deleted! x is like a tiny delete key.",
      },
      {
        id: "step-2",
        instruction: "Press 'u' to undo the last change",
        expectedKeys: ["u"],
        hint: "Press 'u' for undo",
        successMessage: "Undone! You can press u multiple times.",
      },
      {
        id: "step-3",
        instruction: "Press Ctrl+r to redo",
        expectedKeys: ["Ctrl-r"],
        hint: "Press Ctrl+r for redo",
        successMessage: "Redone! Ctrl+r is the opposite of u.",
      },
      {
        id: "step-4",
        instruction: "Press '.' (period) to repeat the last change",
        expectedKeys: ["."],
        hint: "Press the period key",
        successMessage: "Repeated! The dot command is incredibly powerful.",
      },
    ],
  },

  // ============================================
  // NEOVIM - INTERMEDIATE (OPERATORS)
  // ============================================
  {
    id: "vim-delete-operations",
    title: "Delete Operations",
    description: "Learn the delete operator and how it combines with motions",
    category: "neovim",
    difficulty: "intermediate",
    estimatedMinutes: 7,
    steps: [
      {
        id: "step-1",
        instruction: "The 'd' key is the delete operator. Press 'd' to start a delete...",
        expectedKeys: ["d"],
        hint: "Press 'd' for delete",
        successMessage: "Waiting for a motion! d + motion = delete that motion.",
      },
      {
        id: "step-2",
        instruction: "Press 'w' to delete a word (dw = delete word)",
        expectedKeys: ["w"],
        hint: "Press 'w' to complete 'dw' - delete word",
        successMessage: "Word deleted! dw = delete word.",
      },
      {
        id: "step-3",
        instruction: "Press 'd' twice (dd) to delete the entire line",
        expectedKeys: ["d"],
        hint: "Press 'd' again for dd",
        successMessage: "Line deleted! dd is the most common delete command.",
      },
      {
        id: "step-4",
        instruction: "Press 'D' (capital D) to delete from cursor to end of line",
        expectedKeys: ["D"],
        hint: "Press Shift+d for D",
        successMessage: "Deleted to end! D is shorthand for d$.",
      },
      {
        id: "step-5",
        instruction: "Try d$ - press 'd' first",
        expectedKeys: ["d"],
        hint: "Press 'd'",
        successMessage: "Now add the motion...",
      },
      {
        id: "step-6",
        instruction: "Press '$' to delete to end of line",
        expectedKeys: ["$"],
        hint: "Press Shift+4 for $",
        successMessage: "d$ does the same as D! You can combine d with ANY motion.",
      },
    ],
  },
  {
    id: "vim-yank-put",
    title: "Yank (Copy) and Put (Paste)",
    description: "Copy and paste the Vim way",
    category: "neovim",
    difficulty: "intermediate",
    estimatedMinutes: 6,
    steps: [
      {
        id: "step-1",
        instruction: "'y' is the yank (copy) operator. Press 'y' to start.",
        expectedKeys: ["y"],
        hint: "Press 'y' for yank",
        successMessage: "Waiting for a motion! y + motion = yank that motion.",
      },
      {
        id: "step-2",
        instruction: "Press 'y' again to yank the entire line (yy)",
        expectedKeys: ["y"],
        hint: "Press 'y' again for yy",
        successMessage: "Line yanked! yy copies the whole line.",
      },
      {
        id: "step-3",
        instruction: "Press 'p' to put (paste) after the cursor",
        expectedKeys: ["p"],
        hint: "Press 'p' for put",
        successMessage: "Pasted after! The line appears below the current line.",
      },
      {
        id: "step-4",
        instruction: "Press 'P' (capital P) to put before the cursor",
        expectedKeys: ["P"],
        hint: "Press Shift+p for P",
        successMessage: "Pasted before! P puts above/before, p puts below/after.",
      },
      {
        id: "step-5",
        instruction: "Yank a word: press 'y' first",
        expectedKeys: ["y"],
        hint: "Press 'y'",
        successMessage: "Now add the motion...",
      },
      {
        id: "step-6",
        instruction: "Press 'w' to yank a word (yw)",
        expectedKeys: ["w"],
        hint: "Press 'w' to complete yw",
        successMessage: "Word yanked! Remember: delete (d) also copies to the register.",
      },
    ],
  },
  {
    id: "vim-change-operations",
    title: "Change Operations",
    description: "Delete and enter insert mode in one command",
    category: "neovim",
    difficulty: "intermediate",
    estimatedMinutes: 5,
    steps: [
      {
        id: "step-1",
        instruction: "'c' is change: delete + enter insert mode. Press 'c' to start.",
        expectedKeys: ["c"],
        hint: "Press 'c' for change",
        successMessage: "Waiting for a motion! c + motion = change that motion.",
      },
      {
        id: "step-2",
        instruction: "Press 'w' to change a word (cw = change word)",
        expectedKeys: ["w"],
        hint: "Press 'w' to complete cw",
        successMessage: "Word deleted, now in insert mode! Type the replacement.",
      },
      {
        id: "step-3",
        instruction: "Press Escape to return to normal mode",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "Back to normal!",
      },
      {
        id: "step-4",
        instruction: "Press 'c' twice (cc) to change the entire line",
        expectedKeys: ["c"],
        hint: "Press 'c' to start cc",
        successMessage: "Now press c again...",
      },
      {
        id: "step-5",
        instruction: "Press 'c' again to complete cc",
        expectedKeys: ["c"],
        hint: "Press 'c' again",
        successMessage: "Line cleared, in insert mode! cc = S (substitute line).",
      },
      {
        id: "step-6",
        instruction: "Press Escape, then 'C' to change to end of line",
        expectedKeys: ["Escape"],
        hint: "Press Escape first",
        successMessage: "Back to normal!",
      },
      {
        id: "step-7",
        instruction: "Press 'C' (capital C) to change from cursor to end of line",
        expectedKeys: ["C"],
        hint: "Press Shift+c for C",
        successMessage: "C = c$ - change to end of line!",
      },
    ],
  },
  {
    id: "vim-text-objects",
    title: "Text Objects",
    description: "Select and operate on words, sentences, paragraphs, and more",
    category: "neovim",
    difficulty: "intermediate",
    estimatedMinutes: 8,
    steps: [
      {
        id: "step-1",
        instruction: "Text objects work with operators. Try 'ciw' - change inner word. Press 'c' first.",
        expectedKeys: ["c"],
        hint: "Press 'c' for change",
        successMessage: "Now add the text object...",
      },
      {
        id: "step-2",
        instruction: "Press 'i' for 'inner'",
        expectedKeys: ["i"],
        hint: "Press 'i' for inner",
        successMessage: "Inner means without surrounding spaces. Now specify what...",
      },
      {
        id: "step-3",
        instruction: "Press 'w' for word - this completes 'ciw' (change inner word)",
        expectedKeys: ["w"],
        hint: "Press 'w' for word",
        successMessage: "Changed inner word! The word is deleted, you're in insert mode.",
      },
      {
        id: "step-4",
        instruction: "Press Escape, then try 'di\"' to delete inside quotes. Press 'd' first.",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "Back to normal!",
      },
      {
        id: "step-5",
        instruction: "Press 'd' for delete",
        expectedKeys: ["d"],
        hint: "Press 'd'",
        successMessage: "Now 'i' for inner...",
      },
      {
        id: "step-6",
        instruction: "Press 'i' for inner",
        expectedKeys: ["i"],
        hint: "Press 'i'",
        successMessage: "Now specify what to delete inside...",
      },
      {
        id: "step-7",
        instruction: "Press '\"' to delete inside double quotes",
        expectedKeys: ['"'],
        hint: "Press Shift+' for \"",
        successMessage: "Deleted inside quotes! di\" works with any quotes: di' di` di(",
      },
      {
        id: "step-8",
        instruction: "'a' includes the surrounding. Try 'daw' - delete a word. Press 'd'.",
        expectedKeys: ["d"],
        hint: "Press 'd'",
        successMessage: "Now 'a' for around...",
      },
      {
        id: "step-9",
        instruction: "Press 'a' for 'a' (around/including)",
        expectedKeys: ["a"],
        hint: "Press 'a'",
        successMessage: "This will include surrounding spaces...",
      },
      {
        id: "step-10",
        instruction: "Press 'w' to complete 'daw'",
        expectedKeys: ["w"],
        hint: "Press 'w'",
        successMessage: "Deleted word AND surrounding space! 'i' = inner, 'a' = around.",
      },
    ],
  },

  // ============================================
  // NEOVIM - LEADER KEY & MODERN FEATURES
  // ============================================
  {
    id: "vim-leader-basics",
    title: "The Leader Key",
    description: "Space is your command launcher in modern Neovim",
    category: "neovim",
    difficulty: "intermediate",
    estimatedMinutes: 5,
    steps: [
      {
        id: "step-1",
        instruction: "The Leader key (Space) opens up hundreds of commands. Press Space now.",
        expectedKeys: [" "],
        hint: "Press the Space bar",
        successMessage: "Leader activated! A menu should appear showing options.",
      },
      {
        id: "step-2",
        instruction: "Press Escape to close the menu",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "Space + letter combos are your power tools!",
      },
    ],
  },
  {
    id: "vim-file-navigation",
    title: "Finding Files",
    description: "Navigate your project with fuzzy file finding",
    category: "neovim",
    difficulty: "intermediate",
    estimatedMinutes: 6,
    steps: [
      {
        id: "step-1",
        instruction: "Press Space twice quickly (Space Space) to open the file finder",
        expectedKeys: [" "],
        hint: "Press Space bar",
        successMessage: "File finder! Type to fuzzy search files.",
      },
      {
        id: "step-2",
        instruction: "Press Escape to close",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "Closed!",
      },
      {
        id: "step-3",
        instruction: "Space+e opens the file explorer. Press Space.",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-4",
        instruction: "Press 'e' for explorer",
        expectedKeys: ["e"],
        hint: "Press 'e'",
        successMessage: "File explorer! Navigate with j/k, open with Enter.",
      },
      {
        id: "step-5",
        instruction: "Press Escape, then try Space+/ for grep search",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "Closed!",
      },
      {
        id: "step-6",
        instruction: "Press Space for leader",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-7",
        instruction: "Press '/' to search (grep) across all files",
        expectedKeys: ["/"],
        hint: "Press /",
        successMessage: "Grep search! This searches content, not filenames.",
      },
    ],
  },
  {
    id: "vim-lsp-navigation",
    title: "Code Navigation with LSP",
    description: "Jump to definitions, references, and more",
    category: "neovim",
    difficulty: "intermediate",
    estimatedMinutes: 7,
    steps: [
      {
        id: "step-1",
        instruction: "Press 'g' then 'd' to go to definition (gd)",
        expectedKeys: ["g"],
        hint: "Press 'g' first",
        successMessage: "Now press 'd'...",
      },
      {
        id: "step-2",
        instruction: "Press 'd' to complete 'gd' (go to definition)",
        expectedKeys: ["d"],
        hint: "Press 'd'",
        successMessage: "gd = go to definition. Works with LSP!",
      },
      {
        id: "step-3",
        instruction: "Press 'g' then 'r' to find all references (gr)",
        expectedKeys: ["g"],
        hint: "Press 'g' first",
        successMessage: "Now press 'r'...",
      },
      {
        id: "step-4",
        instruction: "Press 'r' to complete 'gr' (go to references)",
        expectedKeys: ["r"],
        hint: "Press 'r'",
        successMessage: "gr = go to references. See everywhere a symbol is used!",
      },
      {
        id: "step-5",
        instruction: "Press 'K' (capital K) to show documentation/hover info",
        expectedKeys: ["K"],
        hint: "Press Shift+k for capital K",
        successMessage: "Hover docs! K shows you info about what's under cursor.",
      },
      {
        id: "step-6",
        instruction: "Navigate to next diagnostic (error/warning). Press '[' then 'd'",
        expectedKeys: ["["],
        hint: "Press '['",
        successMessage: "Now press 'd'...",
      },
      {
        id: "step-7",
        instruction: "Press 'd' to complete '[d' (previous diagnostic)",
        expectedKeys: ["d"],
        hint: "Press 'd'",
        successMessage: "[d = previous error, ]d = next error. Jump between issues!",
      },
    ],
  },
  {
    id: "vim-git",
    title: "Git Integration",
    description: "Git commands with Space+g",
    category: "neovim",
    difficulty: "intermediate",
    estimatedMinutes: 6,
    steps: [
      {
        id: "step-1",
        instruction: "Press Space for leader",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-2",
        instruction: "Press 'g' for git commands",
        expectedKeys: ["g"],
        hint: "Press 'g'",
        successMessage: "Git menu! s=status, b=branches, l=log",
      },
      {
        id: "step-3",
        instruction: "Press 's' for git status",
        expectedKeys: ["s"],
        hint: "Press 's'",
        successMessage: "Git status! See changed files.",
      },
      {
        id: "step-4",
        instruction: "Press Escape, then Space+g+g for Lazygit",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "Closed!",
      },
      {
        id: "step-5",
        instruction: "Press Space",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-6",
        instruction: "Press 'g' for git",
        expectedKeys: ["g"],
        hint: "Press 'g'",
        successMessage: "Git menu...",
      },
      {
        id: "step-7",
        instruction: "Press 'g' again for Lazygit",
        expectedKeys: ["g"],
        hint: "Press 'g' again",
        successMessage: "Lazygit! A full git UI in your terminal.",
      },
    ],
  },
  {
    id: "vim-search-operations",
    title: "Search Operations",
    description: "Search text in buffers and across projects",
    category: "neovim",
    difficulty: "intermediate",
    estimatedMinutes: 6,
    steps: [
      {
        id: "step-1",
        instruction: "Press '/' to start a forward search",
        expectedKeys: ["/"],
        hint: "Press '/'",
        successMessage: "Type your search pattern, then Enter to search.",
      },
      {
        id: "step-2",
        instruction: "Press Escape to cancel. Then press '*' to search for word under cursor.",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "Cancelled!",
      },
      {
        id: "step-3",
        instruction: "Press '*' to search forward for the word under cursor",
        expectedKeys: ["*"],
        hint: "Press Shift+8 for *",
        successMessage: "Searching for this word! Press n for next, N for previous.",
      },
      {
        id: "step-4",
        instruction: "Press 'n' to go to the next match",
        expectedKeys: ["n"],
        hint: "Press 'n'",
        successMessage: "Next match! n goes forward, N goes backward.",
      },
      {
        id: "step-5",
        instruction: "Press Space+s+w for search word across project",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-6",
        instruction: "Press 's' for search",
        expectedKeys: ["s"],
        hint: "Press 's'",
        successMessage: "Search menu...",
      },
      {
        id: "step-7",
        instruction: "Press 'w' for word search",
        expectedKeys: ["w"],
        hint: "Press 'w'",
        successMessage: "Search word! This greps the word across all project files.",
      },
    ],
  },
  {
    id: "vim-terminal",
    title: "Terminal Integration",
    description: "Use terminals inside Neovim",
    category: "neovim",
    difficulty: "intermediate",
    estimatedMinutes: 4,
    steps: [
      {
        id: "step-1",
        instruction: "Open a floating terminal. Press Space",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-2",
        instruction: "Press 't' for terminal",
        expectedKeys: ["t"],
        hint: "Press 't'",
        successMessage: "Terminal menu...",
      },
      {
        id: "step-3",
        instruction: "Press 'f' for floating terminal",
        expectedKeys: ["f"],
        hint: "Press 'f'",
        successMessage: "Floating terminal! Run commands without leaving Neovim.",
      },
      {
        id: "step-4",
        instruction: "Press Escape, then Ctrl+/ to toggle terminal",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "Closed!",
      },
      {
        id: "step-5",
        instruction: "Press Ctrl+/ to toggle terminal",
        expectedKeys: ["Ctrl-/"],
        hint: "Press Ctrl+/",
        successMessage: "Toggle terminal! Ctrl+/ is the quick way to show/hide.",
      },
    ],
  },
  {
    id: "vim-formatting",
    title: "Code Formatting & Actions",
    description: "Format code and use code actions",
    category: "neovim",
    difficulty: "intermediate",
    estimatedMinutes: 5,
    steps: [
      {
        id: "step-1",
        instruction: "Format the current file. Press Space",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-2",
        instruction: "Press 'v' then 'v' for format (Space+vv)",
        expectedKeys: ["v"],
        hint: "Press 'v'",
        successMessage: "Now press 'v' again...",
      },
      {
        id: "step-3",
        instruction: "Press 'v' again to format",
        expectedKeys: ["v"],
        hint: "Press 'v'",
        successMessage: "Code formatted! Uses your configured formatter.",
      },
      {
        id: "step-4",
        instruction: "Rename a symbol. Press Space",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-5",
        instruction: "Press 'r' then 'e' for rename (Space+re)",
        expectedKeys: ["r"],
        hint: "Press 'r'",
        successMessage: "Now press 'e'...",
      },
      {
        id: "step-6",
        instruction: "Press 'e' to rename",
        expectedKeys: ["e"],
        hint: "Press 'e'",
        successMessage: "Rename! Type new name, Enter to confirm. Updates all references!",
      },
      {
        id: "step-7",
        instruction: "Code actions fix issues. Press Space",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-8",
        instruction: "Press 'c' then 'a' for code action (Space+ca)",
        expectedKeys: ["c"],
        hint: "Press 'c'",
        successMessage: "Now press 'a'...",
      },
      {
        id: "step-9",
        instruction: "Press 'a' for code action",
        expectedKeys: ["a"],
        hint: "Press 'a'",
        successMessage: "Code actions! Quick fixes, imports, refactoring options.",
      },
    ],
  },
  {
    id: "vim-ai-assistant",
    title: "AI Assistant (Opencode)",
    description: "Use AI to help with coding",
    category: "neovim",
    difficulty: "intermediate",
    estimatedMinutes: 5,
    steps: [
      {
        id: "step-1",
        instruction: "Ask AI about your code. Press Space",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-2",
        instruction: "Press 'o' for opencode",
        expectedKeys: ["o"],
        hint: "Press 'o'",
        successMessage: "Opencode menu...",
      },
      {
        id: "step-3",
        instruction: "Press 'a' to ask with context",
        expectedKeys: ["a"],
        hint: "Press 'a'",
        successMessage: "Ask AI! Type your question about the code.",
      },
      {
        id: "step-4",
        instruction: "Press Escape, then try Space+o+x for actions menu",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "Closed!",
      },
      {
        id: "step-5",
        instruction: "Press Space",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-6",
        instruction: "Press 'o' for opencode",
        expectedKeys: ["o"],
        hint: "Press 'o'",
        successMessage: "Opencode menu...",
      },
      {
        id: "step-7",
        instruction: "Press 'x' for action menu",
        expectedKeys: ["x"],
        hint: "Press 'x'",
        successMessage: "Action menu! Choose: explain, fix, review, optimize, etc.",
      },
    ],
  },

  // ============================================
  // NEOVIM - ADVANCED
  // ============================================
  {
    id: "vim-macros",
    title: "Recording Macros",
    description: "Record and replay sequences of commands",
    category: "neovim",
    difficulty: "advanced",
    estimatedMinutes: 6,
    steps: [
      {
        id: "step-1",
        instruction: "Start recording a macro. Press 'q' then a letter (e.g., 'a')",
        expectedKeys: ["q"],
        hint: "Press 'q' to start recording",
        successMessage: "Now press a letter to name the macro...",
      },
      {
        id: "step-2",
        instruction: "Press 'a' to record into register 'a'",
        expectedKeys: ["a"],
        hint: "Press 'a'",
        successMessage: "Recording into @a! Everything you do is recorded.",
      },
      {
        id: "step-3",
        instruction: "Do some action - press 'x' to delete a character",
        expectedKeys: ["x"],
        hint: "Press 'x'",
        successMessage: "Action recorded!",
      },
      {
        id: "step-4",
        instruction: "Press 'q' again to stop recording",
        expectedKeys: ["q"],
        hint: "Press 'q' to stop",
        successMessage: "Macro recorded in @a!",
      },
      {
        id: "step-5",
        instruction: "Play the macro with '@a' - press '@' first",
        expectedKeys: ["@"],
        hint: "Press Shift+2 for @",
        successMessage: "Now press 'a' to play @a...",
      },
      {
        id: "step-6",
        instruction: "Press 'a' to play the macro",
        expectedKeys: ["a"],
        hint: "Press 'a'",
        successMessage: "Macro played! Use @@ to repeat the last macro.",
      },
    ],
  },
  {
    id: "vim-marks",
    title: "Using Marks",
    description: "Set bookmarks in your code and jump to them",
    category: "neovim",
    difficulty: "advanced",
    estimatedMinutes: 5,
    steps: [
      {
        id: "step-1",
        instruction: "Set a mark at the current position. Press 'm' then a letter",
        expectedKeys: ["m"],
        hint: "Press 'm' to set a mark",
        successMessage: "Now press a letter to name the mark...",
      },
      {
        id: "step-2",
        instruction: "Press 'a' to create mark 'a'",
        expectedKeys: ["a"],
        hint: "Press 'a'",
        successMessage: "Mark 'a' set! This position is bookmarked.",
      },
      {
        id: "step-3",
        instruction: "Move somewhere else - press 'G' to go to bottom of file",
        expectedKeys: ["G"],
        hint: "Press Shift+g for G",
        successMessage: "Now you're somewhere else...",
      },
      {
        id: "step-4",
        instruction: "Jump back to mark 'a'. Press backtick (`) then 'a'",
        expectedKeys: ["`"],
        hint: "Press backtick (below Escape key)",
        successMessage: "Now press 'a' to jump to mark a...",
      },
      {
        id: "step-5",
        instruction: "Press 'a' to jump to mark 'a'",
        expectedKeys: ["a"],
        hint: "Press 'a'",
        successMessage: "Jumped to exact position! Use ' (single quote) to jump to line only.",
      },
    ],
  },
  {
    id: "vim-registers",
    title: "Using Registers",
    description: "Multiple clipboards and special registers",
    category: "neovim",
    difficulty: "advanced",
    estimatedMinutes: 6,
    steps: [
      {
        id: "step-1",
        instruction: "Yank into a named register. Press '\"' first to specify register",
        expectedKeys: ['"'],
        hint: "Press Shift+' for \"",
        successMessage: "Now specify which register...",
      },
      {
        id: "step-2",
        instruction: "Press 'a' for register 'a'",
        expectedKeys: ["a"],
        hint: "Press 'a'",
        successMessage: "Now yank with 'yy'...",
      },
      {
        id: "step-3",
        instruction: "Press 'y' twice to yank line into register 'a'",
        expectedKeys: ["y"],
        hint: "Press 'y'",
        successMessage: "Now press 'y' again...",
      },
      {
        id: "step-4",
        instruction: "Press 'y' again to complete yank",
        expectedKeys: ["y"],
        hint: "Press 'y'",
        successMessage: "Yanked into @a! You can have 26 registers (a-z).",
      },
      {
        id: "step-5",
        instruction: "Paste from register 'a'. Press '\"' first",
        expectedKeys: ['"'],
        hint: "Press Shift+' for \"",
        successMessage: "Now specify register...",
      },
      {
        id: "step-6",
        instruction: "Press 'a' for register 'a'",
        expectedKeys: ["a"],
        hint: "Press 'a'",
        successMessage: "Now paste...",
      },
      {
        id: "step-7",
        instruction: "Press 'p' to paste from register 'a'",
        expectedKeys: ["p"],
        hint: "Press 'p'",
        successMessage: "Pasted from @a! Each register keeps its content until overwritten.",
      },
    ],
  },

  // ============================================
  // WORKFLOW LESSONS
  // ============================================
  {
    id: "workflow-basic",
    title: "Basic Workflow: tmux + Neovim",
    description: "Put it all together for a basic development workflow",
    category: "workflow",
    difficulty: "beginner",
    estimatedMinutes: 10,
    steps: [
      {
        id: "step-1",
        instruction: "Start by splitting tmux horizontally: Ctrl+a then -",
        expectedKeys: ["Ctrl-a"],
        hint: "Press Ctrl+a for the prefix",
        successMessage: "Prefix ready!",
      },
      {
        id: "step-2",
        instruction: "Press - to split",
        expectedKeys: ["-"],
        hint: "Press minus key",
        successMessage: "Split! Now you have editor on top, terminal on bottom.",
      },
      {
        id: "step-3",
        instruction: "Navigate to the bottom pane: Ctrl+a then j",
        expectedKeys: ["Ctrl-a"],
        hint: "Press Ctrl+a",
        successMessage: "Prefix!",
      },
      {
        id: "step-4",
        instruction: "Press j to move down",
        expectedKeys: ["j"],
        hint: "Press j to go down",
        successMessage: "Now in bottom pane - run tests, git commands here!",
      },
      {
        id: "step-5",
        instruction: "Go back up to edit code: Ctrl+a then k",
        expectedKeys: ["Ctrl-a"],
        hint: "Press Ctrl+a",
        successMessage: "Prefix!",
      },
      {
        id: "step-6",
        instruction: "Press k to move up",
        expectedKeys: ["k"],
        hint: "Press k to go up",
        successMessage: "Back to editor pane! This is the core workflow.",
      },
    ],
  },
  {
    id: "workflow-git",
    title: "Git Workflow",
    description: "Using Git effectively with Space+g commands",
    category: "workflow",
    difficulty: "intermediate",
    estimatedMinutes: 8,
    steps: [
      {
        id: "step-1",
        instruction: "Check git status: Space+g+s",
        expectedKeys: [" "],
        hint: "Press Space for leader",
        successMessage: "Leader active!",
      },
      {
        id: "step-2",
        instruction: "Press 'g' for git",
        expectedKeys: ["g"],
        hint: "Press g",
        successMessage: "Git menu...",
      },
      {
        id: "step-3",
        instruction: "Press 's' for status",
        expectedKeys: ["s"],
        hint: "Press s",
        successMessage: "Git status! See what's changed.",
      },
      {
        id: "step-4",
        instruction: "Press Escape, then view diff: Space+g+d",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "Closed!",
      },
      {
        id: "step-5",
        instruction: "Press Space",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-6",
        instruction: "Press 'g' for git",
        expectedKeys: ["g"],
        hint: "Press g",
        successMessage: "Git menu...",
      },
      {
        id: "step-7",
        instruction: "Press 'd' for diff",
        expectedKeys: ["d"],
        hint: "Press d",
        successMessage: "Git diff! Review your changes before committing.",
      },
      {
        id: "step-8",
        instruction: "Press Escape, then open Lazygit: Space+g+g",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "Closed!",
      },
      {
        id: "step-9",
        instruction: "Press Space",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-10",
        instruction: "Press 'g' for git",
        expectedKeys: ["g"],
        hint: "Press g",
        successMessage: "Git menu...",
      },
      {
        id: "step-11",
        instruction: "Press 'g' for Lazygit",
        expectedKeys: ["g"],
        hint: "Press g again",
        successMessage: "Lazygit! Full git UI - stage, commit, push all in one place.",
      },
    ],
  },
  {
    id: "workflow-search",
    title: "Searching Your Codebase",
    description: "Find anything with grep and fuzzy finding",
    category: "workflow",
    difficulty: "intermediate",
    estimatedMinutes: 7,
    steps: [
      {
        id: "step-1",
        instruction: "Find a file by name: Space Space",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active! Press Space again...",
      },
      {
        id: "step-2",
        instruction: "Press Space again for file finder",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "File finder! Type to fuzzy search filenames.",
      },
      {
        id: "step-3",
        instruction: "Press Escape, then search file contents: Space /",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "Closed!",
      },
      {
        id: "step-4",
        instruction: "Press Space",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-5",
        instruction: "Press '/' for grep search",
        expectedKeys: ["/"],
        hint: "Press /",
        successMessage: "Grep! Search text across all files.",
      },
      {
        id: "step-6",
        instruction: "Press Escape, then search keymaps: Space s k",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "Closed!",
      },
      {
        id: "step-7",
        instruction: "Press Space",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-8",
        instruction: "Press 's' for search",
        expectedKeys: ["s"],
        hint: "Press s",
        successMessage: "Search menu...",
      },
      {
        id: "step-9",
        instruction: "Press 'k' for keymaps",
        expectedKeys: ["k"],
        hint: "Press k",
        successMessage: "Keymaps! Search all your keyboard shortcuts.",
      },
    ],
  },
  {
    id: "workflow-debugging",
    title: "Debugging Workflow",
    description: "Navigate errors and fix issues efficiently",
    category: "workflow",
    difficulty: "intermediate",
    estimatedMinutes: 7,
    steps: [
      {
        id: "step-1",
        instruction: "Jump to the next error/diagnostic: ]d",
        expectedKeys: ["]"],
        hint: "Press ]",
        successMessage: "Now press d...",
      },
      {
        id: "step-2",
        instruction: "Press 'd' to complete ]d",
        expectedKeys: ["d"],
        hint: "Press d",
        successMessage: "Jumped to next error! ]d forward, [d backward.",
      },
      {
        id: "step-3",
        instruction: "See error details: Space e",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-4",
        instruction: "Press 'e' for diagnostic float",
        expectedKeys: ["e"],
        hint: "Press e",
        successMessage: "Error details! Read the full diagnostic message.",
      },
      {
        id: "step-5",
        instruction: "Press Escape, then try code action: Space c a",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "Closed!",
      },
      {
        id: "step-6",
        instruction: "Press Space",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-7",
        instruction: "Press 'c' for code",
        expectedKeys: ["c"],
        hint: "Press c",
        successMessage: "Code menu...",
      },
      {
        id: "step-8",
        instruction: "Press 'a' for code action",
        expectedKeys: ["a"],
        hint: "Press a",
        successMessage: "Code actions! Quick fixes, auto-imports, and more.",
      },
    ],
  },
  {
    id: "workflow-refactoring",
    title: "Refactoring Workflow",
    description: "Rename, format, and restructure code",
    category: "workflow",
    difficulty: "advanced",
    estimatedMinutes: 8,
    steps: [
      {
        id: "step-1",
        instruction: "Rename a symbol across all files: Space r e",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-2",
        instruction: "Press 'r' for rename/refactor",
        expectedKeys: ["r"],
        hint: "Press r",
        successMessage: "Refactor menu...",
      },
      {
        id: "step-3",
        instruction: "Press 'e' for rename",
        expectedKeys: ["e"],
        hint: "Press e",
        successMessage: "Rename! Type new name, updates ALL references.",
      },
      {
        id: "step-4",
        instruction: "Press Escape, then format file: Space v v",
        expectedKeys: ["Escape"],
        hint: "Press Escape",
        successMessage: "Closed!",
      },
      {
        id: "step-5",
        instruction: "Press Space",
        expectedKeys: [" "],
        hint: "Press Space",
        successMessage: "Leader active!",
      },
      {
        id: "step-6",
        instruction: "Press 'v' for visual/format",
        expectedKeys: ["v"],
        hint: "Press v",
        successMessage: "Format menu...",
      },
      {
        id: "step-7",
        instruction: "Press 'v' again to format",
        expectedKeys: ["v"],
        hint: "Press v",
        successMessage: "Formatted! Uses your formatter (prettier, black, etc).",
      },
      {
        id: "step-8",
        instruction: "Change inside quotes with 'ci\"' - press 'c'",
        expectedKeys: ["c"],
        hint: "Press c",
        successMessage: "Change operator...",
      },
      {
        id: "step-9",
        instruction: "Press 'i' for inner",
        expectedKeys: ["i"],
        hint: "Press i",
        successMessage: "Inner...",
      },
      {
        id: "step-10",
        instruction: "Press '\"' for inside quotes",
        expectedKeys: ['"'],
        hint: "Press Shift+'",
        successMessage: "Changed inside quotes! Powerful for refactoring strings.",
      },
    ],
  },
];

export const getLessonsByCategory = (category: "tmux" | "neovim" | "workflow") =>
  lessons.filter((l) => l.category === category);

export const getLessonsByDifficulty = (difficulty: "beginner" | "intermediate" | "advanced") =>
  lessons.filter((l) => l.difficulty === difficulty);

export const getLesson = (id: string) => lessons.find((l) => l.id === id);

export const getNextLesson = (currentId: string): Lesson | undefined => {
  const currentIndex = lessons.findIndex((l) => l.id === currentId);
  return lessons[currentIndex + 1];
};

export const getLessonProgress = (
  completedLessons: string[]
): { total: number; completed: number; percentage: number } => {
  return {
    total: lessons.length,
    completed: completedLessons.length,
    percentage: Math.round((completedLessons.length / lessons.length) * 100),
  };
};

export const getTotalLessons = () => lessons.length;
export const getTmuxLessons = () => lessons.filter((l) => l.category === "tmux").length;
export const getNeovimLessons = () => lessons.filter((l) => l.category === "neovim").length;
export const getWorkflowLessons = () => lessons.filter((l) => l.category === "workflow").length;
